export enum Connecteur {
  TYPE_1 = 'Type 1',
  TYPE2 = 'Type 2',
  CHAdeMO = ' CHAdeMo',
  Tesla = 'Tesla',
  Tesla2 = 'Tesla 2',
  P17 = ' P17',
  Marechal = 'Marechal',
  IEC309DC = 'IEC309DC',
  Type3A = 'Type3A',
  TypeD = 'TypeD',
  TeslaHPWC = 'TeslaHPWC',
  ChinaPart2 = 'ChinaPart2',
  DomestiqueUK = 'DomestiqueUK',
  ComboCCSUSA = 'ComboCCSUSA',
  TeslaUSA = 'TeslaUSA',
  CHT25 = 'CHT25',
  DomestiqueIT = 'DomestiqueIT',
  CHT13 = 'CHT13',
  PriseAVCON = 'PriseAVCON',
  DomestiqueUE = 'DomestiqueUE',
  ComboCCSE = 'ComboCCSE',
}
