export enum Emplacement {
  Entreprise = 'Entreprise',
  Hôtel = 'Hôtel',
  Particulier = 'Particulier',
  Parking = 'Parking',
  Gare = 'Gare',
  Stationservice = 'Station-service',
  Restaurant = 'Restaurant',
  Voirie = 'Voirie',
  Ecole = 'École',
  Autoroute = 'Autoroute',
  Autre = 'Autre',
  Sharedplugs = 'Hide privately shared plugs',
  Freechargers = 'Free chargers only',
  Hideplugs = 'Hide plugs that are not accessible 24/24h',
}
